[build]
  command = "npm run build"
  publish = "dist"

# Configuración de redirecciones
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true
  headers = {Content-Type = "application/xml"}

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

# Redirección SPA (manejar rutas del lado del cliente)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de encabezados globales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.googletagmanager.com https://*.google-analytics.com https://*.analytics.google.com https://*.firebaseio.com https://www.googleapis.com https://www.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://tagmanager.google.com; img-src 'self' data: https: https://*.google-analytics.com https://*.googletagmanager.com https://*.google.com https://*.g.doubleclick.net; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.google-analytics.com https://*.google.com https://*.g.doubleclick.net https://*.googleapis.com https://*.firebaseio.com wss://*.firebaseio.com https://*.googletagmanager.com; frame-src 'self' https://*.firebaseapp.com https://*.googletagmanager.com https://*.google.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests;"

# Configuración específica para sitemap.xml
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"
    Access-Control-Allow-Origin = "*"

# Configuración específica para robots.txt
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=3600"
